
export const BIHAR_MENU_ITEMS = [
    // Specials & Gramin Bhojan (Rural Delights)
    { name: "Litti Chokha (2 Pcs)", price: 60, category: "Specials" },
    { name: "Litti Murga Combo", price: 250, category: "Specials" },
    { name: "Sattu Paratha (With Curd)", price: 80, category: "Specials" },
    { name: "Champaran Mutton Handi (Half)", price: 450, category: "Specials" },
    { name: "Champaran Chicken Handi (Half)", price: 300, category: "Specials" },
    { name: "Dehati Chicken Curry", price: 280, category: "Main Course" },
    { name: "Rohu Fish Curry (2 Pcs)", price: 180, category: "Main Course" },
    { name: "Chana Ghugni & Moodhi", price: 50, category: "Snacks" },
    { name: "Dal Pitha (4 Pcs)", price: 80, category: "Specials" },
    { name: "Khichdi Chokha Papad Combo", price: 120, category: "Specials" },
    { name: "Kadhi Badi (With Rice)", price: 130, category: "Specials" },
    { name: "Chura Dahi (Curd Beaten Rice)", price: 90, category: "Specials" },
    { name: "Bachka Platter (Assorted Fritters)", price: 100, category: "Starters" },
    { name: "Aloo Bhujia (Side Dish)", price: 60, category: "Sides" },
    { name: "Baingan Bharta (Chokha)", price: 50, category: "Sides" },
    { name: "Ol Ki Chatni (Suran Pickle)", price: 30, category: "Sides" },

    // Starters
    { name: "Chicken Lollipop (6 Pcs)", price: 220, category: "Starters" },
    { name: "Chicken Chilli (Dry)", price: 240, category: "Starters" },
    { name: "Paneer Chilli (Dry)", price: 200, category: "Starters" },
    { name: "Veg Manchurian", price: 160, category: "Starters" },
    { name: "Crispy Corn", price: 150, category: "Starters" },
    { name: "Chicken 65", price: 230, category: "Starters" },
    { name: "Mushroom Chilli", price: 210, category: "Starters" },
    { name: "Gobi Manchurian", price: 150, category: "Starters" },
    { name: "Hara Bhara Kabab", price: 180, category: "Starters" },

    // Main Course (Veg)
    { name: "Paneer Butter Masala", price: 240, category: "Main Course" },
    { name: "Kadhai Paneer", price: 230, category: "Main Course" },
    { name: "Mushroom Do Pyaza", price: 220, category: "Main Course" },
    { name: "Malai Kofta", price: 240, category: "Main Course" },
    { name: "Mix Veg", price: 180, category: "Main Course" },
    { name: "Dal Fry", price: 120, category: "Main Course" },
    { name: "Dal Tadka", price: 140, category: "Main Course" },
    { name: "Aloo Dum (Banarasi Style)", price: 160, category: "Main Course" },
    { name: "Matar Paneer", price: 200, category: "Main Course" },
    { name: "Chana Masala", price: 150, category: "Main Course" },
    { name: "Palak Paneer", price: 210, category: "Main Course" },

    // Main Course (Non-Veg)
    { name: "Chicken Masala", price: 260, category: "Main Course" },
    { name: "Mutton Rogan Josh", price: 420, category: "Main Course" },
    { name: "Egg Curry (2 Eggs)", price: 140, category: "Main Course" },
    { name: "Butter Chicken", price: 280, category: "Main Course" },
    { name: "Fish Curry (Mustard Gravy)", price: 200, category: "Main Course" },
    { name: "Chicken Korma", price: 270, category: "Main Course" },

    // Rice & Biryani
    { name: "Chicken Biryani", price: 220, category: "Rice" },
    { name: "Mutton Biryani", price: 350, category: "Rice" },
    { name: "Veg Pulao", price: 150, category: "Rice" },
    { name: "Jeera Rice", price: 110, category: "Rice" },
    { name: "Steamed Rice", price: 80, category: "Rice" },
    { name: "Veg Biryani", price: 180, category: "Rice" },
    { name: "Egg Biryani", price: 200, category: "Rice" },
    { name: "Curd Rice", price: 130, category: "Rice" },

    // Breads
    { name: "Tandoori Roti", price: 20, category: "Breads" },
    { name: "Butter Roti", price: 25, category: "Breads" },
    { name: "Plain Naan", price: 40, category: "Breads" },
    { name: "Butter Naan", price: 50, category: "Breads" },
    { name: "Garlic Naan", price: 60, category: "Breads" },
    { name: "Lacha Paratha", price: 45, category: "Breads" },
    { name: "Tawa Roti (Plain Chapatis)", price: 10, category: "Breads" },
    { name: "Makki Ki Roti", price: 30, category: "Breads" },
    { name: "Missi Roti", price: 35, category: "Breads" },
    { name: "Aloo Paratha", price: 60, category: "Breads" },
    { name: "Paneer Paratha", price: 80, category: "Breads" },

    // Desserts & Beverages
    { name: "Gulab Jamun (2 Pcs)", price: 50, category: "Desserts" },
    { name: "Rasgulla (2 Pcs)", price: 40, category: "Desserts" },
    { name: "Masala Cold Drink", price: 50, category: "Beverages" },
    { name: "Lassi", price: 60, category: "Beverages" },
    { name: "Mineral Water", price: 20, category: "Beverages" },
    { name: "Makhana Kheer", price: 90, category: "Desserts" },
    { name: "Tilkut (Seasonal)", price: 50, category: "Desserts" },
    { name: "Anarsa", price: 40, category: "Desserts" },
    { name: "Thekua (4 Pcs)", price: 40, category: "Desserts" },
    { name: "Malpua (2 Pcs)", price: 70, category: "Desserts" },
    { name: "Sattu Sharbat (Namkeen/Meetha)", price: 40, category: "Beverages" },
    { name: "Fresh Lime Soda", price: 50, category: "Beverages" },
    { name: "Coca Cola (250ml)", price: 40, category: "Beverages" },
    { name: "Sprite (250ml)", price: 40, category: "Beverages" },
    { name: "Thums Up (250ml)", price: 40, category: "Beverages" },
    { name: "Dairy Milk Silk", price: 80, category: "Desserts" },
    { name: "Dairy Milk Chocolate", price: 40, category: "Desserts" },
    { name: "KitKat", price: 30, category: "Desserts" },
    { name: "Ice Cream (Vanilla/Choco)", price: 60, category: "Desserts" },
];
